version: "3.7"
services:
  app:
    build:
      args:
        user: radthoc
        uid: 1001
      context: ./
      dockerfile: Dockerfile
    image: nfibo
    container_name: nfibo-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
